### ISSUE TITLE
[Feature Request] Switch to using External Component

### ISSUE THREAD

**Issue by ShayBox** [wildekek/rdtech-esphome#12]
This could probably be handled using an external component script, so it can just be sourced https://esphome.io/components/external_components

**Comment by wildekek** [comment]
Not sure what "this" means in your suggestion. Since I only use the official ESPHome components, I don't understand what problem you're trying to solve here and what should become and external component. Perhaps you mean abstracting some functionality in the ESPHome packages feature?

**Comment by ShayBox** [comment]
This script/config, ESPHome has External Components now, so you can turn this into an external component, and everyone can just link to this repo in their config instead of copying the config entirely, it's like sourcing part of the config from a remote source at build time.

**Comment by wildekek** [comment]
I agree that importing this config and adding it to your existing config would be useful and clean.

Either you don’t understand how components work in the context of ESPHome, or I fail to understand how you imagine this would work. Example: ‘Modbus’ is an ESPHome component, it is c-code that represents itself as a component in ESPHome. I fail to see how and why i would create a component to abstract away this config, it makes no sense to me.

Again, I think what you want is an external package, not a component. If not, i’m open to your perspective but i fail to see the logic of creating a new component.

**Comment by ShayBox** [comment]
Yes it would be a somewhat big change, it's not as simple as importing a yaml file within a yaml file. ESPHome "External Components" use Python, you would have to use the esphome library in Python to create the same behavior as the current yaml. See [here](https://community.home-assistant.io/t/solved-working-with-custom-external-component/313343) to get an idea on how this system works.

**Comment by wildekek** [comment]
I now understand your perspective, thanks for explaining!

I don't think I want to use an external component for this though. I feel they should be used for supporting MCU's or other hardware, things that don't run their own software stack like these power supplies. For me, having the configuration of the device in YAML makes sense, as it can be easily modified and adapted.

I **do** want to look at packages and updates though, making the config cleaner like [this example](https://github.com/EverythingSmartHome/everything-presence-lite/blob/main/everything-presence-lite-ha.yaml).

If you feel like forking the repo and creating an external component, you have my full support though.

**Comment by ShayBox** [comment]
I didn't know you could actually include yaml like that, that seems like a better idea for this case since it's possible without custom components, unfortunately I still need to learn external components because my iFan03 uses custom components, which are deprecated and going to be removed.
